k9s:
  ui:
    #skin: catppuccin-mocha
    #skin: catppuccin-macchiato
    #skin: catppuccin-frappe
    #skin: catppuccin-latte
    skin: catppuccin-mocha-transparent
    #skin: catppuccin-macchiato-transparent
    #skin: catppuccin-frappe-transparent
    #skin: catppuccin-latte-transparent
